### ISSUE TITLE
Clean command

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#11]
I suppose that the purpose of the script that execute the command `npm run clean` is for delete the `/lib` folder.

I guess a cli-command like `rm -rf /lib` could do the same job. And you save a script file for it. Let me your opinion about it 😄 . If you like the change, I leave a PR implemented #12 , if not just reject 😉

**Comment by amwmedia** [comment]
the problem with that is that, if a developer is on windows, the commandline doesn't HAVE the `rm` command, so it will fail.

**Comment by calcaide** [comment]
You are right. In that case I used to work with [rimraf](https://www.npmjs.com/package/rimraf), You can use it directly in npm commands, but I suppose that you want to take advantage of the Promise API that del gives you, right?

**Comment by amwmedia** [comment]
I think I originally brought in `del` because it uses a promise api, but I'm sure I'm even using the promise version of the api anywhere. Probably rimraf would work too, it's just what I chose to use at the time.

**Comment by calcaide** [comment]
Ok, In essence, is just to save the clean script, because in code is the same use. I leave in my fork a [branch](https://github.com/calcaide/node-plop/tree/issue-11) working with RimRaf. If you like it I can push a PR. There is no compromise If you prefer to stay with Del, it is also a good choice 😉

**Comment by amwmedia** [comment]
I'd have to see if I'm using `del` anywhere else. But yeah, unless there's a reason to switch over to another library, I'd rather leave `del` in place. :-)

**Comment by calcaide** [comment]
Nice, just in case I will keep the branch alive for a while.
