### ISSUE TITLE
Support for extension dropping

### ISSUE THREAD

**Issue by maraisr** [amwmedia/node-plop#112]
If you have a directory, with say `templates/{index.js,test.js}.hbs` - and run the action `addMany`, could that potentially support an additional property to drop of a file extension?

as in:

```js
module.exports = function(plop) {
	plop.setGenerator('component', {
		description: 'Generate a new component',
		prompts: [
			{
				type: 'input',
				name: 'name',
				message: 'component name?',
			},
		],
		actions() {
			return [
				{
					type: 'addMany',
					destination: 'lib/components/{{ pascalCase name }}.{{ ext }}',
					base: 'templates/component/',
                                        ext: 'without-hbs', // or 'as-is', or ext(incomingFile:string): string
					templateFiles: 'templates/component/**/*',
				},
			];
		},
	});
};

```

**Comment by maraisr** [comment]
I'm working an PR for this feature, I'll try and KISS it, but happy for you to guide me on an implementation spec. :100:

**Comment by amwmedia** [comment]
hmm, is there a reason you wouldn't want to just remove the `.hbs` from the template files? They will still be processed as templates, even without the hbs extension.

**Comment by maraisr** [comment]
I get where you're coming from. 2 things really, with a `.hbs` extension, my IDE would make it look better, and secondly, auto format on save breaks these files horribly. Nothing I can't solve locally, but still, at the end of the day, its a handlebars file, that produces a js file for instance - so it's not a .js file, its a .hbs file.

**Comment by amwmedia** [comment]
Hmmm, I see what you mean. I actually think that it might make sense to just remove the `.hbs` extension by default when adding the file. We could then have a config option that would turn off that behavior. I would guess that 99% of the time that plop is being used to add an `hsb` file with the `addMany` action, the user doesn't intend to actually add a handlebars template file. 🤔

**Comment by amwmedia** [comment]
If you'd like to PR this, you would likely look at making the change within the addMany action itself. You could add some logic to [where the `add` action `path` is being generated](https://github.com/amwmedia/node-plop/blob/master/src/actions/addMany.js#L40) so that if the result ends in `.hbs`, that suffix is removed.
