### ISSUE TITLE
Bad path to creating files

### ISSUE THREAD

**Issue by toryas** [amwmedia/node-plop#114]
Hi, 

I try to load te plopfile from global lib but, when I try to add some files the path where I want create is wrong

This is the file that run node-plop:

```javascript
#!/usr/bin/env node

'use strict';

const nodePlop = require('node-plop'); 
const plop = nodePlop(__dirname + `/plopfile.js`);

async function createMs(){
    let msGen = plop.getGenerator('ms');
    try{
      let data = await msGen.runPrompts();
      let result = await msGen.runActions(data);
      
      let changes = result.changes;
      let fails = result.failures;
      console.log(fails);
      console.log(changes);

  }catch(error){
    console.log(error);
 }

createMs();
```

I packing this function whit the plofile and then install  `npm i -g lib.tgz` then calling this using `mg new ms`.

When try to write de proyect folder throws this error, because is trying to write in the path where plopfile is located no where comand is called

```
[ { type: 'addMany',
    path: '',
    error: 'EACCES: permission denied, mkdir \'/usr/lib/node_modules/ms-node-generator/my-microservice\'' } ]
[]
```

**Comment by amwmedia** [comment]
Yes, that is correct. plop uses the path of the plopfile as the base for all other paths. This is because the plopfile exists to enforce a certain structure that (most of the time) is not based on the user's `cwd`. If you want to use the `cwd` in the construction of paths, you can do that, but it won't be the default behavior. All actions support the `data` property. Which can be used to add your own data to the prompt data.

```
plop.setGenerator('test', {
  ...
  actions: [{
    ...
    path: '{{rootPath}}/some/folder/file.ext',
    data: {rootPath: process.cwd()}
  }]
});
```

**Comment by toryas** [comment]
> Yes, that is correct. plop uses the path of the plopfile as the base for all other paths. This is because the plopfile exists to enforce a certain structure that (most of the time) is not based on the user's `cwd`. If you want to use the `cwd` in the construction of paths, you can do that, but it won't be the default behavior. All actions support the `data` property. Which can be used to add your own data to the prompt data.
> 
> ```
> plop.setGenerator('test', {
>   ...
>   actions: [{
>     ...
>     path: '{{rootPath}}/some/folder/file.ext',
>     data: {rootPath: process.cwd()}
>   }]
> });
> ```
reading the source code of node-plop, I found that nodePlop() accept a config.
So I did use this config:

```javascript
const plop = nodePlop(__dirname + `/plopfile.js`,{destBasePath:process.cwd()});
```

**Comment by amwmedia** [comment]
yes, this will also work. However, just know that this will force all generators in that plopfile to treat this path as their base path. If that's what you need for your use case, great. 👍
