### ISSUE TITLE
Change Babel plugins for a ES2015 preset

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#13]
Babel is using an important amount of plugins. In order to minimize this list of plugins, I suggest using a Babel [ES2015 preset](https://babeljs.io/docs/plugins/preset-es2015/) that include all these plugins.

**Comment by calcaide** [comment]
I use the ES2015 preset and the test were failing. For that reason finally I use [babel-preset-es2015-node](https://www.npmjs.com/package/babel-preset-es2015-node) and I had to tell AVA to use the project Babel configuration instead of the built-in babel support ([AVA comes with ES2015 support](https://github.com/avajs/ava#es2015-support))

I leave a PR with that changes working #14

**Comment by amwmedia** [comment]
nice find! I started with es2015 preset, but regenerator was breaking the code. So I basically took that preset and removed regenerator. Looks like this preset is more appropriate. :-)

**Comment by calcaide** [comment]
Thanks! yes, was the regenerator what broke the tests. I don't understand you about remove the regenerator, what do you mean?

**Comment by amwmedia** [comment]
basically took all of the transform plugins that make up the "es2015" preset, removed the regenerator plugin from that list, and used that set of plugins instead of the preset. That's why the plugin list was so long.

**Comment by calcaide** [comment]
Ah ok. I asked you, because the line that broke the tests was `const runGeneratorPrompts = co.wrap(function* (genObject)` and I thought maybe you are thinking in other approach or something. Nevermind, now I get it.

**Comment by amwmedia** [comment]
ah, yeah, that's a bit confusing because of mixed terms (plop generator and es6 generators)
