### ISSUE TITLE
Add ESLint in a build process

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#15]
Add ESLint in a build process instead of JSHint in a IDE/Text editor.

**Comment by amwmedia** [comment]
take a look at [pre-commit](https://github.com/observing/pre-commit). I've used this before and it's very handy. I also want to get a CI server in place to run this after the push happens. But a pre-commit hook saves so much headache.

**Comment by calcaide** [comment]
I added a ESLint configuration file [extending from recommended](http://eslint.org/docs/user-guide/configuring#using-eslintrecommended). 
I added an ESLint configuration file extending from recommended and adding some style rules. I made some minor changes to complete ESLint.

I leave a PR #16

**Comment by calcaide** [comment]
Sorry, I made the PR and the comment before notice yours, I will take a look.

**Comment by calcaide** [comment]
To be honest, I have never been using a Git hook. But I read the pre-commit you suggest and looks interesting. As I can understand with a quick read is a workaround to have a CI server?

**Comment by amwmedia** [comment]
don't worry about it, I'll work on getting pre-commit hooked up to this once I take a look and pull it in.

**Comment by amwmedia** [comment]
I commented before I saw that you had a PR in

**Comment by calcaide** [comment]
If you want, I am pretty interested in try to set up a CI server. I think we have different options like [Travis](https://travis-ci.org/) I never used it yet, and I hear a lot about it. What do you think? Do you want to go ahead with the pre-commit? Or do you want to set up a CI Server? As I say I can take care of it.

**Comment by amwmedia** [comment]
If you'd like to put some time into setting up a CI server, I think that would be good. I would think Travis or CircleCI would be fine. We don't really need deployment or anything, but being able to run the tests for each commit or on a PR branch would be nice.

I'll probably setup `pre-commit` eventually as well. I don't think using one means you can't do the other as well.

**Comment by calcaide** [comment]
For sure, 100% agree with your opinion 😃 . Today my work time is almost over, but if you want, tomorrow I can take car of first update de PR with the `pre-commit` and then I will go for a Travis CI. If you want to take the `pre-commit` let me know, but as I said earlier I never used it, so I like to try new things.

**Comment by amwmedia** [comment]
go for it :-) I have some other things that are going to take priority for a little bit. But I should be able to continue to make some progress on things, it just won't be quite as frequent for the next few days at least.

**Comment by calcaide** [comment]
Thanks! this week I have some time, so I will work in Plop a little each day. 👍
