### ISSUE TITLE
Refactor plop-base.js

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#2]
I think could be a good Idea to refactor a plop-base.js. Use ES6 standard modules and ES Classes. Also use const or let (depend on the case) instead of var. What do you think @amwmedia ?

Of course, I will fork the project, open a branch referring to this issue and push a pull request.

_I mention you because [here](https://github.com/amwmedia/plop/issues/43#issuecomment-256655042) and I do not want to step on your work._

**Comment by amwmedia** [comment]
sounds good, why don't you go ahead and take a stab at it. I just did fs-promise.js this morning. Planning to tackle generator-runner.js next. I just pushed my fs-promise work up.

**Comment by amwmedia** [comment]
if you run `npm run develop`, it should get you going with the babel compile step and ava test runner as you develop

**Comment by calcaide** [comment]
Today I do not have much time to dedicate it (here almost 5 pm), but I think tomorrow morning I will make the pull request.

Thanks for the tip 😉

**Comment by calcaide** [comment]
Finally, I will postpone this issue, when I started to work, I realized that I have never used AVA testing. I decided to start refactoring the tests so while I am learning how use AVA I am producing something. Sorry for the mess.

**Comment by amwmedia** [comment]
Are you still planning to take this on? If so, you'll want to make sure you pull in the latest code that was just pushed up. It makes [a small change to](https://github.com/amwmedia/node-plop/commit/9f09a2f278af4d5a7aa60b37129cc3cda6b2df03#diff-8ed3dc0d8928b7abcbc15356a7cfd26bR54) the plop-base.js file that you were planning to refactor.

**Comment by calcaide** [comment]
Yeah, I do it right now. I am starting to refactor it.
I am not sure if just made a ES6 module and return it as an API, [an example](https://github.com/calcaide/javascript-style-guide/blob/master/README.md#modules--default-export) (more or less like is now with the revealing module pattern) or wrap it the code in a ES6 class.
What do you think about it?

**Comment by amwmedia** [comment]
I think you could definitely use a normal es6 export syntax for this. I didn't use that approach for the `fs-promise-proxy.js` file, because for some reason I thought that the es6 `import`/`export` stuff wasn't working properly in the build process I had in place. I just tried it again and it worked fine 🙄

**Comment by amwmedia** [comment]
so I'm not doing another minor refactor of `fs-promise-proxy.js` and `generator-runner.js`

**Comment by amwmedia** [comment]
[updated](https://github.com/amwmedia/node-plop/commit/f37c2991223b1563479b18877ccad9e8626f8b42)

**Comment by calcaide** [comment]
I am trying to [wrap it in a class](https://github.com/calcaide/node-plop/blob/issue-2/src/modules/plop-base.js) but I did not figure out what is wrong... the test seems not to pass. Also, [I had to change](https://github.com/calcaide/node-plop/blob/issue-2/src/index.js#L13) the way that plop is called.

I will put that refactor in stand by and focus in refactor the tests to an ES6 approach. I guess that will help me to understand better the project.

**Comment by amwmedia** [comment]
if I have a few minutes today, I'll copy your code over and take a look at what might be breaking.

**Comment by calcaide** [comment]
Cool, but maybe the problem is that I don't know yet well the whole project, maybe I am missing something. I feel bad that you spend time on this.

**Comment by amwmedia** [comment]
maybe, but no worries. If I didn't have time or didn't want to look into... I wouldn't be offering. 😄

**Comment by amwmedia** [comment]
I looked into this and submitted a patch to both files. These changes fix the issue as far as I can tell. Have a look when you have a moment

**Comment by amwmedia** [comment]
I'll be interested to get your feedback on the solution. I feel like the benefits of using a `class` vs the revealing module pattern for this particular instance might not outweigh the downside of having to always make sure that the functions are executed with the proper `this` context.

**Comment by calcaide** [comment]
Forgive Me, this morning half asleep I made a mistake with git... I deleted the issue-2 branch and I have reconstructed, yeah, I know big mistake. Actually I applied your solutions and pass the tests but two of them doesn't pass ( I don't know if you also have this issue).

Yeah, I got your point, about the `this` context. Now I have to spend 1/2 hours on other thing, but then I will try to refactor it to a simple ES6 module with the [API approach](https://github.com/calcaide/javascript-style-guide/blob/master/README.md#modules--default-export). I would not use classes so the `this` context disappears, What do you think?

**Comment by amwmedia** [comment]
no problem, I'll take a look, I have the changes I made in a stash still.

The plop-base implementation needs to have some sort of context for each instance. So, if I understand the api approach in the link above, this might not work. each instance of plop-base needs to provide functions that have access to that context. That why I think the `class` approach was good, but because we recompose plop-base with the `runner`, this causes other issues. 

I'm not yet sure what would be best, just throwing my observations out there. 🙂

**Comment by calcaide** [comment]
Just now I updated [with this](https://github.com/calcaide/node-plop/blob/issue-2/src/modules/plop-base.js) it was just a moment to show you what I mean.

Humm... you are pretty right about the context. I will take some time to think about it.

**Comment by amwmedia** [comment]
sounds good, I'll think about it too.

**Comment by amwmedia** [comment]
Right now I'm leaning toward going with an es6 revealing module pattern. Similar to how the [generator runner](https://github.com/calcaide/node-plop/blob/issue-2/src/modules/generator-runner.js#L8) was refactored. Unless you have another idea?

**Comment by amwmedia** [comment]
Oh, and the part I think you might be missing (for the 2 failing tests) might be [this](https://github.com/calcaide/node-plop/pull/2/files#diff-8ed3dc0d8928b7abcbc15356a7cfd26bR61)

**Comment by calcaide** [comment]
Yes! this morning a made a complete mess... Now, is working with a class approach and the tests are passing. For sure the singleton ES6 module with an API approach is useless, as you said, we need a new instance. I had not enough time to think about a good solution. I am not familiar yet with the runner and I have to read it and understand it to figure out where are the other issues that you mention.

**Comment by calcaide** [comment]
This afternoon I have no more time to do it, and I don't know if during the weekend I will have time to stay in front of the computer, go ahead with your idea 👍

**Comment by amwmedia** [comment]
I just mentioned the runner as an example of an approach that could work. I do have another way that we could use the `class` structure without some of the same `this` drawbacks. I'll throw it up on a gist so you can look it over and give feedback.

**Comment by amwmedia** [comment]
ah, ok. I'll go ahead with the other approach and we'll talk about a possible refactor in the future if it makes sense.

**Comment by calcaide** [comment]
Just add a comment in the same second hahaha, for sure, I really like to watch different ideas and approaches, so count with me for that 😃 . As you said yesterday, are many important things to do in the project so a future refactor could be a good option too 😉

**Comment by calcaide** [comment]
Now I realize that maybe I misunderstood you. When you said `this` drawbacks, are you referring working in the class, I mean, using this.whatEver every time, or are you referring when you are using the class in other files?

Do not think I want to be bothersome, just I want to be at the same page and understand your point 😉

**Comment by amwmedia** [comment]
no problem, what I meant is that it's kind of a pain that when you pass `plop.setGenerator` through like we do in `index.js`, that we need to make sure we bind that function to the correct `this` context or it won't execute correctly. As apposed to using function closure scopes to isolate the state as we were before.

**Comment by calcaide** [comment]
I guess, I got your point. I think you take a good decision, it is better to leave this refactor to the future. Thanks for the explanation.
