### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#21]
As @amwmedia suggest, Add [pre-commit](https://github.com/observing/pre-commit) to run the tests in each commit or PR.

**Comment by calcaide** [comment]
I added a pre-commit hook that runs test script. @amwmedia  Do you think have to run also eslint or other task?

I leave a PR #22

**Comment by amwmedia** [comment]
I would think that eslint should run in pre-commit, and actually be removed from `npm run develop`. I don't think it makes sense to require lint to pass prior to starting your development work.

**Comment by calcaide** [comment]
Agree with you. When I put there, I was thinking about noticing you in development stage, but as you said, now it makes no sense. I will change and push it the change.

**Comment by calcaide** [comment]
Done.
