### ISSUE TITLE
Error to import nodePlop in typescript when compile to commonjs

### ISSUE THREAD

**Issue by toryas** [amwmedia/node-plop#221]
when import nodePlop like this

```javascript
import nodePlop from "node-plop";
```

I have this error at run:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...../node_modules/node-plop/src/index.js
require() of ES modules is not supported.
require() of /Users/felipenunez/workspace/toryas/npm/simplex/node_modules/node-plop/src/index.js from ...../npm/simplex/packages/cli/dist/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename ...../npm/simplex/node_modules/node-plop/src/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ...../npm/simplex/node_modules/node-plop/package.json.`

this is my tsconfig.ts
```json
{
    "compilerOptions": {
        "module": "CommonJS",
        "target": "ES2017",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "outDir": "dist",
        "sourceMap": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "moduleResolution": "node",
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts",
        "**/*.test.ts"
    ],
    "types": [
        "jest",
        "node"
    ]
}
```

**Comment by crutchcorn** [comment]
This is because, as-of 0.30.0, `node-plop` is an ESM package that requires you to have `type="module"` in your package.json and to migrate to ESM as opposed to CJS, which was node's prior default
