### ISSUE TITLE
Add Typings with .d.ts files

### ISSUE THREAD

**Issue by marcellkiss** [amwmedia/node-plop#28]
It would be such a huge help if you could add typings to the repo. 
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I assume, you'd be faster than me :) Anyway, it's also possible that I'll try to add typings in the near future.

**Comment by amwmedia** [comment]
I'll look into it. I have no interest currently in using Typescript for the source code of node-plop, but if there's a way to create a types declaration that assists developers who are using node-plop and can serve as a first step towards documentation, I'm all for it.

**Comment by marcellkiss** [comment]
Yep, you can add typing files next to the js files, so you don't have to change the current codebase. 👍
