### ISSUE TITLE
Broken on node 4

### ISSUE THREAD

**Issue by gdub22** [amwmedia/node-plop#29]
Getting an error on these default function parameters, which isn't supported in node 4:
https://github.com/amwmedia/node-plop/blob/master/src/modules/node-plop.js#L8

```
function nodePlop(plopfilePath = '', plopCfg = {}) {
SyntaxError: Unexpected token =
```

I see that babel is set up to read the system node version, so you may need to run the build with your machine running node 4 before publishing, or change the engines field in package.json to >= 6

**Comment by amwmedia** [comment]
That's really weird because the CI server is setup to run all the tests on node 4. I'll look into this in the morning

**Comment by amwmedia** [comment]
fixed in v0.5.4

**Comment by amwmedia** [comment]
@gdub22 Thanks for bringing this to my attention. I understand now what the problem was and it shouldn't be an issue in the future :-)

**Comment by gdub22** [comment]
Thanks for the quick fix!
