### ISSUE TITLE
Add more general inputs API

### ISSUE THREAD

**Issue by kristianmandrup** [amwmedia/node-plop#34]
I propose the following to keep it backwards compatible

```js
  return Object.assign({}, generator, {
    runActions: (data) => runner.runGeneratorActions(generator, data),
    runInputs: () => runner.runGeneratorInputs(generator),
    runPrompts: () => runner.runGeneratorPrompts(generator)
  });
```

 Then in `generator-runner` allow for a more general `inputs` method

```
	const runGeneratorInputs = co.wrap(function* (genObject) {
		if (genObject.inputs == null) {
			throw Error(`${genObject.name} has no prompts`);
		}
		return yield genObject.inputs(genObject);
	});

	return {
		runGeneratorActions,
		runGeneratorInputs,
		runGeneratorPrompts
	};
```

**Comment by kristianmandrup** [comment]
Currently when running `plop` I get:

```
13:47 $ plop
(node:16495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: choose has no prompts
```

Using this plop configuration, with changes as described above, `npm link`ed to local `plop` linked to my plop generator

```js
    // Get inputs from the user.
    // That's Inquirer.js doing the job behind the hood.
    prompts: [],
    inputs: (config) => {
      console.log(config)
    },
```

**Comment by kristianmandrup** [comment]
Guess I need to install my local plop globally then? `npm install -g .`

**Comment by kristianmandrup** [comment]
Updated local version and this is indeed the version being used.

```
$ plop -v
1.7.5
```

**Comment by amwmedia** [comment]
Hey Kristian, can you describe for me what the purpose of `inputs` is and what the issue seems to be? I'm not quite connecting the dots here, I think I'm missing some context.

**Comment by kristianmandrup** [comment]
No worries, got it all working. I needed to use your generator as more of a general purpose tool. 
I have graphical designer tool (based on `node-red`) where we want to generate a full Docker project from the nodes using plop, directly from the web browser UI, using a backed service on top of plop. Thus we would send (feed) the inputs directly to the service as an Object, ie. not using prompts.

https://github.com/tecla5/node-plop
https://github.com/tecla5/plop
https://github.com/tecla5/docker-gen/blob/master/plopfile.js

`plopfile.js` will be wrapped as a Promise and can return values similar to results from inquirer prompts :)

```js
    inputs: (config) => {
      console.log(config)
      return {
        name: 'hello'
      }
    },
    // List of actions to take.
    // Here we "add" new files from our templates.
    actions: [{
     // ...
```

**Comment by kristianmandrup** [comment]
Just wanna mention I did some major rework of my own fork of `plop` and `node-plop` to allow running inputs + generators actions as library without any Terminal (args or other) requirements.
Also enabled add to write to a custom "virtual filesystem". Lot's of fancy stuff to make it more flexible for use outside the Terminal. Cheers!

**Comment by amwmedia** [comment]
@kristianmandrup sounds great! Anything you plan to contribute? ;-) So was your `inputs` idea basically a way to bypass the `prompts`? Similar to how you can use the `runActions` function to provide the prompt answers?
