### ISSUE TITLE
Allowing hierarchical prompts

### ISSUE THREAD

**Issue by filipemir** [amwmedia/node-plop#36]
Plop is a wonderful tool, so thank you for developing it 👍🏻

Would it be possible to add support for dynamic prompts defined by a function? Currently, plop expects the prompts to be defined by an object, but I need to prompt the user with different questions depending on the user's previous answers. I'm happy to submit a quick PR but wanted to run it by you first. 

Here is a simplified example illustrating my use case:
```javascript
// prompts.js
function promptForFileName(inquirer, answers = {}) {
	const prompts = inquirer.prompt([{
		type: 'input',
		name: 'name',
		message: 'What should be the name of your new file?'
	}, {
		type: 'confirm',
		name: 'overrideContent',
		message: 'Do you wanna override the default content?'
	}]);

	prompts.then((newAnswers) => {
		Object.assign(newAnswers, answers);
	});

	return prompts;
}

function promptForContent(inquirer, answers = {}) {
	const prompts = inquirer.prompt({
		type: 'input',
		name: 'content',
		message: 'Content:'
	});

	prompts.then((newAnswers) => {
		Object.assign(newAnswers, answers);
	});

	return prompts;
}

module.exports = function(inquirer) {
	const basePrompt = promptForFileName(inquirer);

	return basePrompt.then((answers) => {
		if (answers.overrideContent) {
			return promptForContent(inquirer, answers);
		}

		return basePrompt;
	});
};
```

```js
// plopfile.js
const prompts = require('./prompts');

module.exports = function (plop) {
	plop.setGenerator('dynamic-actions', {
		description: 'another test using an actions function',
		prompts: prompts,
		actions: function(data) {
			if (!data.overrideContent) {
				data.content = 'Default content';
			}

			return [
				{
					type: 'add',
					path: `./${data.name}.txt`,
					template: '{{ content }}'
				}
			];
		}
	});
};
```

**Comment by amwmedia** [comment]
plop defers the prompt process to [inquirer.js](https://github.com/SBoudrias/Inquirer.js). It sounds like you could use the `when` property on the [question object](https://github.com/SBoudrias/Inquirer.js/#question). This should let you set criteria for whether a given prompt will be run.

**Comment by filipemir** [comment]
Good point. I had missed the `when` property, and that should work in my immediate case. I still think this might be a worthwhile addition for more complex prompts. Inquirer supports hierarchical structure of callbacks for prompts. See here: https://github.com/SBoudrias/Inquirer.js/blob/master/examples/hierarchical.js And adding support for that ability in `node-plop` wouldn't require much more than a type check on the generator's prompts. Something like: 
```js
const runGeneratorPrompts = co.wrap(function* (genObject) {
	const prompts = genObject.prompts;

	if (prompts == null) {
		throw Error(`${genObject.name} has no prompts`);
	}

	if (typeof prompts === 'function') {
		return yield prompts(plopfileApi.inquirer);
	}

	return yield plopfileApi.inquirer.prompt(prompts);
});
```

**Comment by amwmedia** [comment]
interesting... I'll look into it.

**Comment by duclet** [comment]
Interesting indeed. I think the `when` property should probably handle most cases. Nevertheless, I could potentially see the need of this feature request when you have questions that can be used multiple times based on different scenarios and the order matters.

**Comment by filipemir** [comment]
I submitted a PR for this. Please take a look and let me know of any feedback. I'd love to see it merged if feasible. For my particular use, the `when` property won't work always. I need to be able to output statements to the user between prompts, which would be easy to do via `console.log` with this functionality. 

Thank you

**Comment by amwmedia** [comment]
accepted with #37
