### ISSUE TITLE
Upgrade Inquirer.js version

### ISSUE THREAD

**Issue by tpizza** [amwmedia/node-plop#44]
This is a request to update the Inquirer dependency to the latest version.

The primary reason is to have this PR integrated in so that we can reference the answers hash in the filter function.

https://github.com/SBoudrias/Inquirer.js/pull/533

Depending on your bandwidth, I may have time to assign this to myself and jump on the update sometime soon.

**Comment by amwmedia** [comment]
thanks! I'll work on getting it in soon. Shouldn't be too difficult 👍

**Comment by amwmedia** [comment]
fixed by PR #46. greenkeeper is now in place as well to help watch the dependencies and ensure they stay up to date.
