### ISSUE TITLE
Cannot add dotfiles (eg: .gitignore) with addMany

### ISSUE THREAD

**Issue by ecwyne** [amwmedia/node-plop#48]
https://github.com/amwmedia/node-plop/blob/master/src/actions/addMany.js#L39

Globby has a [dot option](https://github.com/isaacs/node-glob#dots) that I believe would fix this

**Comment by amwmedia** [comment]
And you believe that having the dot options set to `true` by default would make more sense as opposed to needing to be more specific with your globby definitions?

**Comment by amwmedia** [comment]
I wonder if it would be best to simply support a `dot` option on the action config that is then passed through to `globby`? That way it's simple to get either behavior, but the default behavior is preserved.

**Comment by amwmedia** [comment]
this was fixed in #52 and will be released soon. I'm pulling together a few more changes to release in a batch. stay tuned 👍
