### ISSUE TITLE
Inquirer prompts should have their filter applied during bypass

### ISSUE THREAD

**Issue by cjnickel** [amwmedia/node-plop#54]
Inquirer prompts allow the user to specify a `filter` function on a [question](https://github.com/SBoudrias/Inquirer.js/#objects). Specifying a `filter` works when a prompt is not bypassed. However, it is not executed when bypassing the prompt.

**Expected behavior**:
When bypassing prompts - if there is a `filter` for that prompt then it should be executed.

e.g.
```js
module.exports = plop => {
  plop.setGenerator("container", {
    description: "Generate React container component",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "Container name",
        filter: answer => `${answer}Container`
      }
    ],
    actions: [
      {
        type: "add",
        path: "src/containers/{{pascalCase name}}.js",
        templateFile: "./container.hbs"
      }
    ]
  });
};
```
Screenshot not bypassing prompts:
![image](https://user-images.githubusercontent.com/361566/34081800-db9cc052-e320-11e7-9143-b6503e3e2d20.png)

Screenshot bypassing prompts:
![image](https://user-images.githubusercontent.com/361566/34081807-f05cb592-e320-11e7-9dc3-3fbe85b354db.png)

**Comment by amwmedia** [comment]
Thank you! I'll get to this soon.
