### ISSUE TITLE
Template files without extension are ignored

### ISSUE THREAD

**Issue by mikenikles** [amwmedia/node-plop#57]
Hey,

We ran into an issue where files such as `Dockerfile` or `.babelrc` are ignored because of https://github.com/amwmedia/node-plop/blob/17fb3ff9ee6f61ba9b64751234b0e87714ec7de5/src/actions/addMany.js#L47.

I'm happy to open a PR that removes the `isFile` function together with its use at https://github.com/amwmedia/node-plop/blob/17fb3ff9ee6f61ba9b64751234b0e87714ec7de5/src/actions/addMany.js#L41.

Before I do though, I want to make sure that PR would get accepted. It's quite possible that `isFile` function is required 🤔.

**Comment by amwmedia** [comment]
Seems like we should just refactor this to use `fs.stat` or `fs.statSync` instead of having our own definition of what constitutes a file. @nicoespeon any thoughts?

**Comment by nicoespeon** [comment]
We should keep this filter, but I agree with @amwmedia: to rely on the standard definition of a file instead of a custom implementation would be smarter. I guess it will fix this bug 😄

**Comment by mikenikles** [comment]
Thanks guys, I have since noticed that the code I linked to is the `0.9.0` release. In `master`, it all looks good: https://github.com/amwmedia/node-plop/blob/master/src/actions/addMany.js#L50

I looked at 0.9.0 because `plop` explicitly depends on 0.9.0 as seen at https://github.com/amwmedia/plop/blob/master/package.json#L35.

Also, the latest `node-plop` version available on NPM is 0.9.0 (https://www.npmjs.com/package/node-plop). Is there any chance you could release `master`, which is 0.10.2 and upgrade the dependency in `plop`?

**Comment by amwmedia** [comment]
@mikenikles just an update, plop v2.0 will be releases soon and include this change

**Comment by mikenikles** [comment]
Awesome news, thanks for the update! We ended up with a workaround by configuring a list of the impacted files and use the Add action individually.

Looking forward to 2.0.
