### ISSUE TITLE
Does not copy `.gitignore` files from templates

### ISSUE THREAD

**Issue by crutchcorn** [amwmedia/node-plop#69]
If I have a `.gitignore` file that is in my templates folder, it is not copied into the directory I wish to place my newly generated template into. You can see a code example here:
https://github.com/crutchcorn/generate-me/tree/14370feb32d05f913387929c7ac1359c52ed3b1a

By running `node index.js "Test" y n` and looking into `src/server`, you can see the behavior

**Comment by amwmedia** [comment]
ok, looks like this is a documentation miss. You can pass a `globOptions` attribute into the `addMany` action and that will be passed to globby when it's processed. the glob option you are looking for is `dot: true`

**Comment by crutchcorn** [comment]
I'll look into it more and make a PR into the main `plop` repo to add respective docs.

**Comment by amwmedia** [comment]
here is the [line of interest](https://github.com/amwmedia/node-plop/blob/master/src/actions/addMany.js#L29)

**Comment by crutchcorn** [comment]
Closing issue as it's:
- Not a bug
- Has an open PR that adds proper documentation needed to solve this issue
