### ISSUE TITLE
Rethink test structure

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#7]
The actual test structure using an index (`test.ava.js`) works but is not ideal as we discussed in [here](https://github.com/amwmedia/node-plop/issues/6).

**Comment by calcaide** [comment]
@amwmedia what do you think about [this](https://github.com/calcaide/node-plop/blob/issue-7/tests/basic-plopfile.ava.js) ? It that branch, if you run `npm run develop` just that test works, but I did it to get you opinion as soon as possible.

**Comment by amwmedia** [comment]
I like it! I'd say go ahead and run with this approach if it does the job (I didn't actually pull and run it myself yet).

**Comment by calcaide** [comment]
Ok, yeah, it works fine. I will work on this today.

**Comment by amwmedia** [comment]
take a look, I made some changes to the structure. got rid of the common `mock` folder, created a base `AvaTest` class that abstracts a lot of the boilerplate. 

I also refactored the `async` `await` calls to use `co.wrap`. For some reason async/await was wreaking havoc on my linter. 😦

**Comment by calcaide** [comment]
The changes are good 😉 . It is a pity to lost `async` `await`, I really don't know co.wrap but I was excited to use async, anyway good job with the changes :thumbsup: .

Out of curiosity, what linter are you using?

**Comment by amwmedia** [comment]
I'm running atom and there's a .jshintrc in place right now on this project. I'd be fine with switching it over to eslint and using async/await. I just didn't want to wrestle with that right now, and it was not easy to debug with my linter yelling at me. However, co.wrap/yield is basically the same thing. It just creates a function that returns a promise from a generator function.

**Comment by amwmedia** [comment]
end result is the same, so I didn't want to spend the time to figure it out at the moment when I have so many other things I want to get done on here haha

**Comment by calcaide** [comment]
For sure, doesn't matter 😉 .  I was saying this like, oh man, the first time that I used and works without problems, could be possible? Hahahaha Now we know.

Anyway, the question about the linter it was also related that the other day I thought it could be great having the linter integrated into the building process instead of an IDE/text editor, but like you said, there is other important things in the project and then I forget it. If you also think it could be a great thing in the next days I could open and issue related with this to disscus it, I have this approach in my projects, ESLint integrated with NPM so I can work on this.

**Comment by amwmedia** [comment]
Yeah, I think something like that would be nice. I could pretty easily add the linter process into a pre-commit hook too, which would be nice. I have set that up for some other projects before.
