### ISSUE TITLE
`npm` package is outdated

### ISSUE THREAD

**Issue by crutchcorn** [amwmedia/node-plop#78]
Please update your `npm` package from `0.13.0` to the newest `0.15.0`. There are a few fixes in `0.15.0` that my project relies on and trying to share my fixes to others are difficult

**Comment by amwmedia** [comment]
sorry for the delay, it's published now. I was hoping to roll a few more changes into this release and also do a release of the CLI at the same time, but stuff got busy at work and it dropped off the radar.

Thanks again for your contributions 👍
