### ISSUE TITLE
The tests are broken

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#9]
I didn't try the tests until now and when I tried a get a bunch of SyntaxErrors related with new ES6 features.

**Comment by calcaide** [comment]
I realized the problem that I had it in the first refactor of `test.ava.js` related with transpiling imported modules #6 . I fixed #10 .

In case that you are not having this issue let me know.

**Comment by amwmedia** [comment]
that's strange, all the tests are passing for me as is

**Comment by calcaide** [comment]
Really? yeah... is pretty weird... because when I pull the last changes I had some problems. Today I have no more time, tomorrow I will take some time to look around this. I saw you  merge the PR, but I don't like when things like that happen and I don't know why.
