### ISSUE TITLE
Modify answers array action?

### ISSUE THREAD

**Issue by gregglind** [amwmedia/node-plop#92]
Inquirer gives a named object of 'answers' to each action.

Sometimes I want transformations of those in the templates.  I currently use the handlebars helpers for this.  I repeat them a lot.  

I might be nice if the `plop` object had those answers, and made them modifiable.  This would allow actions like:

```
  plop.setActionType('postProcessAnswers', (answers, config, plop) => {
     plop.answers.someOther = someFunction(answers.firstAnswer);
  });
```
 
This might also be a terrible idea :)  Thanks!

**Comment by amwmedia** [comment]
I believe the answers object is mutable. So you should be able to change it and those changes would be carried to other actions.

**Comment by gregglind** [comment]
If so, how do I find it?  I looked in the `plop` object, and didn't see any `answers`.

Also, plop is still awesome.  Thank for plumbing it together.

**Comment by amwmedia** [comment]
You'd do something like the following. Then in actions that execute later, the `someOther` property should be part of the answers object.

``` javascript
  plop.setActionType('postProcessAnswers', (answers, config, plop) => {
     answers.someOther = someFunction(answers.firstAnswer);
  });
```

**Comment by gregglind** [comment]
Ah, I see.

I tried this first, and received errors about modifying an argument.

Gregg

**Comment by amwmedia** [comment]
I just tried it on my computer and didn't have any problems with it. What version of plop are you using?

**Comment by gregglind** [comment]
Old business I realize, but I claim this is the issue:

```
	const runGeneratorActions = _co2.default.wrap(function* (genObject, data) {
```
That data is the result of runPrompts.  So even if you stick the answers on the generator object (`plop`), it wont propagate to `runActions`.

Use case:
- Mostly I am trying to move a lot more of the parsing of the answers up to the js layer, rather than the moustache transform layer.

Alternative solution:  
- my own modified "doThePlop" script that uses node-plop more directly.
- A 'postPrompts' function that can go into plop.  (This would need Readme and other support.)

**Comment by amwmedia** [comment]
I think I'm missing something here. The prompt data is passed into the actions in the `actions` array one by one. If the data object is modified by an action, that change is propagated to all actions that come after the one that made the change. So it should be possible to supply a `postProcessAnswers` as the first action in the array, and all of your actions should see the changes made.

**Comment by nitsanavni** [comment]
if anybody's still interested, here's an example of @amwmedia sugegstion:
https://github.com/nitsanavni/mm/blob/master/plop/plopfile.ts#L26

we add the `isReact` boolean and use it later here:
https://github.com/nitsanavni/mm/blob/master/plop/templates/test.hbs#L1
